server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${qd.datasource.driver-class-name}
      url: jdbc:mysql://${qd.datasource.host}:${qd.datasource.port}/${qd.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${qd.datasource.username}
      password: ${qd.datasource.password}
  redis:
    host: ${qd.redis.host}
    port: ${qd.redis.port}
    password: ${qd.redis.password}
    database: ${qd.redis.database}
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qd.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      qd:
        mapper: debug
        service: info
        controller: info

qd:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: shiliang
    user-ttl: 7200000
    user-token-name: token
  alioss:
    endpoint: ${qd.alioss.endpoint}
    access-key-id: ${qd.alioss.access-key-id}
    access-key-secret: ${qd.alioss.access-key-secret}
    bucket-name: ${qd.alioss.bucket-name}
  wechat:
    appid: ${qd.wechat.appid}
    secret: ${qd.wechat.secret}
  shop:
    address: ${qd.shop.address}
  baidu:
    ak: ${qd.baidu.ak}

